### ISSUE TITLE
hdf5 tests fail with 1.10.0

### ISSUE THREAD

**Issue by psteinb** [sqeazy/sqeazy#7]
```
$ ./tests/test_hdf5_impl 
Running 22 test cases...
[sqeazy::h5_file, /home/steinbac/development/sqeazy/src/cpp/src/hdf5_utils.hpp:395]     requested dataset IntArray_foo not found in /home/steinbac/development/sqeazy/src/cpp/build/tests/sample.h5
unknown location(0): fatal error in "write_dataset": unknown type
/home/steinbac/development/sqeazy/src/cpp/tests/test_hdf5_impl.cpp(204): last checkpoint
unknown location(0): fatal error in "write_multiple_datasets": unknown type
/home/steinbac/development/sqeazy/src/cpp/tests/test_hdf5_impl.cpp(233): last checkpoint
unknown location(0): fatal error in "write_dataset_with_filter": unknown type
/home/steinbac/development/sqeazy/src/cpp/tests/test_hdf5_impl.cpp(330): last checkpoint
unknown location(0): fatal error in "write_compressed_dataset": unknown type
/home/steinbac/development/sqeazy/src/cpp/tests/test_hdf5_impl.cpp(330): last checkpoint
unknown location(0): fatal error in "roundtrip_compressed_dataset": memory access violation at address: 0x00000008: no mapping at fault address
/home/steinbac/development/sqeazy/src/cpp/tests/test_hdf5_impl.cpp(330): last checkpoint

*** 5 failures detected in test suite "TEST_HDF5_IMPLEMENTATION
```

and

```
$ ./tests/test_hdf5_interface 
Running 16 test cases...
/home/steinbac/development/sqeazy/src/cpp/tests/test_hdf5_interface.cpp(194): error in "write_no_filter": exception thrown by rvalue = SQY_h5_write_UI16(test_output_name.c_str(), dname.c_str(), &data.constant_cube[0], data.dims.size(), &data.dims[0], "")
/home/steinbac/development/sqeazy/src/cpp/tests/test_hdf5_interface.cpp(199): fatal error in "write_no_filter": critical check float(bfs::file_size(test_output_path)) > float(data.size_in_byte) failed [800 <= 1024]
/home/steinbac/development/sqeazy/src/cpp/tests/test_hdf5_interface.cpp(215): error in "roundtrip_no_filter": exception thrown by rvalue = SQY_h5_write_UI16(test_output_name.c_str(), dname.c_str(), &data.constant_cube[0], data.dims.size(), &data.dims[0], "")
/home/steinbac/development/sqeazy/src/cpp/tests/test_hdf5_interface.cpp(226): fatal error in "roundtrip_no_filter": critical check rvalue == 0 failed [1 != 0]
unknown location(0): fatal error in "write_filter": unknown type
/home/steinbac/development/sqeazy/src/cpp/tests/test_hdf5_interface.cpp(226): last checkpoint
unknown location(0): fatal error in "write_compressed_data": unknown type
/home/steinbac/development/sqeazy/src/cpp/tests/test_hdf5_interface.cpp(312): last checkpoint

*** 6 failures detected in test suite "TEST_HDF5_INTERFACE"
```

with c06dc35024bf8b6135d1f1f5caca2c2a048763c1

**Comment by psteinb** [comment]
same code works with 1.8.16

**Comment by psteinb** [comment]
fixed with 3f3768479ee1077ce772229a668f263ddefa6341
